### ISSUE TITLE
Error of Segmentation fault (core dumped) when running deepmreye_example_usage.ipynb

### ISSUE THREAD

**Issue by yqsong96** [DeepMReye/DeepMReye#1]
Hi, 

I have installed the packages and the conda environment (python 3.7) according to your instruction. I downloaded your example data and tried to run `deepmreye_example_usage.ipynb`, but I kept getting the error of Segmentation fault when reaching `preprocess.run_participant(fp_func, dme_template, eyemask_big, eyemask_small, x_edges, y_edges, z_edges)`
(there is no other error):

```
Running participant sub-NDARAA948VFH
Segmentation fault (core dumped)
```

I have a GPU under this environment. Do you have any ideas or solutions about it? Thank you.

**Comment by CYHSM** [comment]
Hey @yqsong96, thanks for the first issue and for using DeepMReye.
A segmentation fault error can be caused by many separate issues but in this case, it's most likely that your RAM is full and therefore it can not preprocess the participant. Can you confirm this by monitoring your RAM usage when running the code? (If true, we will look into ways of optimizing this)

**Comment by yqsong96** [comment]
> Hey @yqsong96, thanks for the first issue and for using DeepMReye. A segmentation fault error can be caused by many separate issues but in this case, it's most likely that your RAM is full and therefore it can not preprocess the participant. Can you confirm this by monitoring your RAM usage when running the code? (If true, we will look into ways of optimizing this)

Thank you for your answer. I have solved this problem and the training is going on well :)
The problem seems irrelevant with RAM, but about the installation method that I used. Now I am using `sys.path.append()` and manually added the DeepMReye path, which works well.

**Comment by CYHSM** [comment]
Very good that it works with the other method. This could still hint at a problem with the pip install though. For further debugging and improving the installation could you let us know which operating system you are using? Thanks.

**Comment by yqsong96** [comment]
> Very good that it works with the other method. This could still hint at a problem with the pip install though. For further debugging and improving the installation could you let us know which operating system you are using? Thanks.

Sure, my system is CentOS Linux 7.9.2009, hope it helps!
