### ISSUE TITLE
Participants' EIDs in Dataset1

### ISSUE THREAD

**Issue by Joy0805** [DeepMReye/DeepMReye#14]
Hi,

As mentioned in the paper, there were 170 participants from HBN included in your dataset 1 used for training and testing. May I know the participants' EIDs? Thank you.

**Comment by CYHSM** [comment]
Sure no problem, I uploaded the participant names here: [all_participants.txt](https://github.com/DeepMReye/DeepMReye/files/8230503/all_participants.txt)
In case the file does not stay online, I pasted the entries below :

> sub-NDARAA948VFH.npz
> sub-NDARAC349YUC.npz
> sub-NDARAC350BZ0.npz
> sub-NDARAC495TJ2.npz
> sub-NDARAD615WLJ.npz
> sub-NDARAE012DGA.npz
> sub-NDARAE358VBE.npz
> sub-NDARAG115LZP.npz
> sub-NDARAG340ERT.npz
> sub-NDARAH503YG1.npz
> sub-NDARAH948UF0.npz
> sub-NDARAK738BGC.npz
> sub-NDARAP176AD1.npz
> sub-NDARAP785CTE.npz
> sub-NDARAT358XM9.npz
> sub-NDARAV610EY3.npz
> sub-NDARAW179AYF.npz
> sub-NDARAX272ZJL.npz
> sub-NDARBE123PWH.npz
> sub-NDARBF805EHN.npz
> sub-NDARBG188RA5.npz
> sub-NDARBH992ARB.npz
> sub-NDARBJ482HJL.npz
> sub-NDARBN365EV3.npz
> sub-NDARBT607PZL.npz
> sub-NDARBU928LV0.npz
> sub-NDARBV167RMU.npz
> sub-NDARBV680AA8.npz
> sub-NDARBW403EVZ.npz
> sub-NDARCA690EBC.npz
> sub-NDARCF052AE0.npz
> sub-NDARCG037CX4.npz
> sub-NDARCG159AAP.npz
> sub-NDARCG438NML.npz
> sub-NDARCG808HDJ.npz
> sub-NDARCJ363KLE.npz
> sub-NDARCK647MU6.npz
> sub-NDARCL016NHB.npz
> sub-NDARCM811CV1.npz
> sub-NDARCR582GKJ.npz
> sub-NDARCU118LMX.npz
> sub-NDARCU736GZ1.npz
> sub-NDARCU865PBV.npz
> sub-NDARCW611MK5.npz
> sub-NDARCZ947WU5.npz
> sub-NDARDA472JE3.npz
> sub-NDARDA573XGG.npz
> sub-NDARDB146NWY.npz
> sub-NDARDD854GF8.npz
> sub-NDARDE877RFH.npz
> sub-NDARDH086ZKK.npz
> sub-NDARDL305BT8.npz
> sub-NDARDL511UND.npz
> sub-NDARDN393BJH.npz
> sub-NDARDN489EXJ.npz
> sub-NDARDR439HY2.npz
> sub-NDARDY150ZP9.npz
> sub-NDARDY776AKH.npz
> sub-NDAREC648WEL.npz
> sub-NDARED628HMQ.npz
> sub-NDAREE675XRY.npz
> sub-NDAREF164ZUJ.npz
> sub-NDAREF848YWD.npz
> sub-NDAREF893ZM8.npz
> sub-NDAREG561ML5.npz
> sub-NDAREH852JE0.npz
> sub-NDAREK255DEE.npz
> sub-NDAREK395BM3.npz
> sub-NDAREK575JNM.npz
> sub-NDAREM731BYM.npz
> sub-NDAREN417DJE.npz
> sub-NDAREN667YTZ.npz
> sub-NDARER970AEF.npz
> sub-NDAREY778CR9.npz
> sub-NDARFA402LMW.npz
> sub-NDARFB908HVX.npz
> sub-NDARFB969EMV.npz
> sub-NDARFE299MWU.npz
> sub-NDARFF061VUK.npz
> sub-NDARFF644ZGD.npz
> sub-NDARFG713PLR.npz
> sub-NDARFJ179MG0.npz
> sub-NDARFK027LB0.npz
> sub-NDARFM229HHA.npz
> sub-NDARFM619GTV.npz
> sub-NDARFM749LF3.npz
> sub-NDARFR820KFF.npz
> sub-NDARFU395UBW.npz
> sub-NDARFU916UZY.npz
> sub-NDARFV780ABD.npz
> sub-NDARFW578RU9.npz
> sub-NDARGA048BD8.npz
> sub-NDARGB000CW8.npz
> sub-NDARGC148JBJ.npz
> sub-NDARGD425PTN.npz
> sub-NDARGE536BGD.npz
> sub-NDARGF367KVL.npz
> sub-NDARGF543PM2.npz
> sub-NDARGH074MU6.npz
> sub-NDARGH842VFY.npz
> sub-NDARGJ395FKP.npz
> sub-NDARGK041TPB.npz
> sub-NDARGK672URV.npz
> sub-NDARGN044FE4.npz
> sub-NDARGT551AFK.npz
> sub-NDARGU844NZ3.npz
> sub-NDARGV781AMW.npz
> sub-NDARGV948BFZ.npz
> sub-NDARGX443CEU.npz
> sub-NDARHC462NGR.npz
> sub-NDARHC825ZFZ.npz
> sub-NDARHD507TEF.npz
> sub-NDARHD931FNA.npz
> sub-NDARHG065YHQ.npz
> sub-NDARHG152GZC.npz
> sub-NDARHG188YE9.npz
> sub-NDARHX963YU1.npz
> sub-NDARJF517HC8.npz
> sub-NDARJG298YVA.npz
> sub-NDARJH492TVW.npz
> sub-NDARKD064EVC.npz
> sub-NDARKK000PNQ.npz
> sub-NDARKV807EMJ.npz
> sub-NDARKX665ZD3.npz
> sub-NDARKZ634RVX.npz
> sub-NDARLU939YX4.npz
> sub-NDARMY873XG5.npz
> sub-NDARND697FLK.npz
> sub-NDARNK740ZVM.npz
> sub-NDARNM708YTF.npz
> sub-NDARNU770PM5.npz
> sub-NDARPD855ARC.npz
> sub-NDARPE752VYE.npz
> sub-NDARPF459CME.npz
> sub-NDARPX838GCD.npz
> sub-NDARPZ344ZGE.npz
> sub-NDARRB901DWV.npz
> sub-NDARRL426AD5.npz
> sub-NDARRM073JKA.npz
> sub-NDARRW974PEF.npz
> sub-NDARRX800KW8.npz
> sub-NDARRX897XV1.npz
> sub-NDARRZ927VC3.npz
> sub-NDARTB203DU7.npz
> sub-NDARTC865YNZ.npz
> sub-NDARTT272WT5.npz
> sub-NDARUY730ANT.npz
> sub-NDARVB902GA5.npz
> sub-NDARVC195NLH.npz
> sub-NDARVN363NNQ.npz
> sub-NDARVP285RXV.npz
> sub-NDARWA433WYZ.npz
> sub-NDARWH779MZ2.npz
> sub-NDARWJ498CZY.npz
> sub-NDARWK104FLX.npz
> sub-NDARWM656UWL.npz
> sub-NDARWV568MEU.npz
> sub-NDARXD345GBN.npz
> sub-NDARXD710RLN.npz
> sub-NDARXE193CZ1.npz
> sub-NDARXL697DA6.npz
> sub-NDARXR346UT5.npz
> sub-NDARXZ902NFM.npz
> sub-NDARYB392JWP.npz
> sub-NDARYC466ER1.npz
> sub-NDARYE379GGT.npz
> sub-NDARYM334BZ5.npz
> sub-NDARZJ587UZU.npz
> sub-NDARZK601NG9.npz
> sub-NDARZM903TNL.npz

Hope these are the ones you are looking for, let me know how it goes.

**Comment by Joy0805** [comment]
Thank you very much!
