### ISSUE TITLE
Missing library libpng16.16.dylib on Mac

### ISSUE THREAD

**Issue by WeeXee** [DeepMReye/DeepMReye#16]
I've tried to run the demo but many bugs appeared:
**Code test:**
```python
# Import modules and add library to path
import sys
sys.path.insert(0, "/Users/admin/Desktop/Github")
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0" # Change to os.environ["CUDA_VISIBLE_DEVICES"] = "" if you dont have access to a GPU
import numpy as np 
import pandas as pd
import pickle

# DeepMReye imports
from deepmreye import architecture, train, analyse, preprocess
from deepmreye.util import util, data_generator, model_opts

# Initialize plotly figures
from plotly.offline import init_notebook_mode 
init_notebook_mode(connected = True)

# Make sure the output width is adjusted for better export as HTML
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:70% !important; }</style>"))
display(HTML("<style>.output_result { max-width:70% !important; }</style>"))

# Autoreload modules
%load_ext autoreload
%autoreload 2
```

**Bug report:**
```python
ImportError                               Traceback (most recent call last)
/var/folders/w3/l91cnb1d7dvdh581bynsm_n80000gp/T/ipykernel_22011/2184068996.py in <module>
      9 
     10 # DeepMReye imports
---> 11 from deepmreye import architecture, train, analyse, preprocess
     12 from deepmreye.util import util, data_generator, model_opts
     13 

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/deepmreye/__init__.py in <module>
      1 from . import util
----> 2 from . import preprocess
      3 from . import architecture
      4 from . import train
      5 from . import analyse

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/deepmreye/preprocess.py in <module>
      2 import pickle
      3 import numpy as np
----> 4 import ants
      5 import matplotlib.pyplot as plt
      6 from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/__init__.py in <module>
      5     pass
      6 
----> 7 from .core import *
      8 from .utils import *
      9 from .segmentation import *

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/core/__init__.py in <module>
      1 
----> 2 from .ants_image import *
      3 from .ants_image_io import *
      4 
      5 from .ants_transform import *

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/core/ants_image.py in <module>
     27 import inspect
     28 
---> 29 from .. import registration, segmentation, utils, viz
     30 from . import ants_image_io as iio2
     31 

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/registration/__init__.py in <module>
      1 
      2 
----> 3 from .affine_initializer import *
      4 from .apply_transforms import *
      5 from .create_jacobian_determinant_image import *

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/registration/affine_initializer.py in <module>
      5 from tempfile import mktemp
      6 
----> 7 from .. import utils
      8 
      9 def affine_initializer(fixed_image, moving_image, search_factor=20,

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/utils/__init__.py in <module>
      1 from .add_noise_to_image import *
----> 2 from .bias_correction import *
      3 from .channels import *
      4 from .convert_nibabel import *
      5 from .crop_image import *

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/utils/bias_correction.py in <module>
      2 
      3 
----> 4 from . import process_args as pargs
      5 from .get_mask import get_mask
      6 from .iMath import iMath

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/utils/process_args.py in <module>
     12 
     13 from ..core import ants_image as iio
---> 14 from .. import lib
     15 
     16 _short_ptype_map = {

~/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/lib/__init__.py in <module>
      1 ## LOCAL ##
----> 2 from .addNoiseToImage import *
      3 from .antiAlias import *
      4 from .antsImage import *
      5 from .antsImageClone import *

ImportError: dlopen(/Users/admin/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/lib/addNoiseToImage.cpython-37m-darwin.so, 0x0002): Library not loaded: /opt/X11/lib/libpng16.16.dylib
  Referenced from: /Users/admin/miniconda3/envs/deepmreye/lib/python3.7/site-packages/ants/lib/addNoiseToImage.cpython-37m-darwin.so
  Reason: tried: '/opt/X11/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
```

*Python version: Python 3.7.13*

**Pip list:**

Package                 Version
----------------------- -------------------
absl-py                 0.15.0
antspyx                 0.3.3
appnope                 0.1.3
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
astunparse              1.6.3
attrs                   21.4.0
backcall                0.2.0
bcrypt                  3.2.2
beautifulsoup4          4.11.1
bleach                  5.0.1
cached-property         1.5.2
cachetools              4.2.4
certifi                 2022.6.15
cffi                    1.15.1
charset-normalizer      2.1.0
chart-studio            1.1.0
clang                   5.0
cmake                   3.22.5
cryptography            37.0.2
cycler                  0.11.0
debugpy                 1.6.0
decorator               5.1.1
deepmreye               0.1.dev147+gcabc3f0
defusedxml              0.7.1
entrypoints             0.4
fastjsonschema          2.15.3
flatbuffers             1.12
fonttools               4.33.3
gast                    0.4.0
google-auth             1.35.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.47.0
h5py                    3.1.0
idna                    3.3
imageio                 2.19.3
importlib-metadata      4.12.0
importlib-resources     5.8.0
ipykernel               6.15.0
ipython                 7.34.0
ipython-genutils        0.2.0
ipywidgets              7.7.1
jedi                    0.18.1
Jinja2                  3.1.2
joblib                  1.1.0
jsonschema              4.6.1
jupyter                 1.0.0
jupyter-client          7.3.4
jupyter-console         6.4.4
jupyter-core            4.10.0
jupyterlab-pygments     0.2.2
jupyterlab-widgets      1.1.1
keras                   2.6.0
Keras-Preprocessing     1.1.2
kiwisolver              1.4.3
Markdown                3.3.7
MarkupSafe              2.1.1
matplotlib              3.5.2
matplotlib-inline       0.1.3
mistune                 0.8.4
nbclient                0.6.6
nbconvert               6.5.0
nbformat                5.4.0
nest-asyncio            1.5.5
networkx                2.6.3
nibabel                 4.0.1
notebook                6.4.12
numpy                   1.19.5
oauthlib                3.2.0
opt-einsum              3.3.0
packaging               21.3
pandas                  1.3.5
pandocfilters           1.5.0
paramiko                2.11.0
parso                   0.8.3
patsy                   0.5.2
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.2.0
pip                     21.2.2
plotly                  5.9.0
prometheus-client       0.14.1
prompt-toolkit          3.0.30
protobuf                3.19.4
psutil                  5.9.1
ptyprocess              0.7.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
Pygments                2.12.0
PyNaCl                  1.5.0
pyparsing               3.0.9
pyrsistent              0.18.1
python-dateutil         2.8.2
pytz                    2022.1
PyWavelets              1.3.0
PyYAML                  6.0
pyzmq                   23.2.0
qtconsole               5.3.1
QtPy                    2.1.0
requests                2.28.1
requests-oauthlib       1.3.1
retrying                1.3.3
rsa                     4.8
scikit-image            0.19.3
scikit-learn            1.0.2
scipy                   1.7.3
Send2Trash              1.8.0
setuptools              61.2.0
six                     1.15.0
soupsieve               2.3.2.post1
statsmodels             0.13.2
tenacity                8.0.1
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow              2.6.5
tensorflow-estimator    2.6.0
termcolor               1.1.0
terminado               0.15.0
threadpoolctl           3.1.0
tifffile                2021.11.2
tinycss2                1.1.1
tornado                 6.2
traitlets               5.3.0
typing-extensions       3.10.0.2
urllib3                 1.26.9
wcwidth                 0.2.5
webcolors               1.12
webencodings            0.5.1
Werkzeug                2.1.2
wheel                   0.37.1
widgetsnbextension      3.6.1
wrapt                   1.12.1
zipp                    3.8.0

**Links I've tried:**

[Stackoverflow](https://stackoverflow.com/questions/22631026/dyld-library-not-loaded-usr-local-lib-libpng16-16-dylib-with-anything-php-rel)
[Homebrew](https://stackoverflow.com/questions/41113448/homebrew-error-no-formulae-found-in-taps)

**Comment by Naubody** [comment]
Thanks for raising this issue.
Did ANTsPy install correctly? If not, could you try installing it manually?
See installation Option 1 for help: https://github.com/DeepMReye/DeepMReye

**Comment by Naubody** [comment]
@WeeXee Did you find out what the issue was? If so, what was it? If not, how can we help you?

**Comment by Remi-Gau** [comment]
Remember that we tried to fix this at the time. But installing the missing library did not work as expected.
We went down the docker road in the end.

Would suggest closing the issue and maybe renaming it to reflect the missing library problem.
