### ISSUE TITLE
No link to the calibration script in the doc

### ISSUE THREAD

**Issue by Remi-Gau** [DeepMReye/DeepMReye#2]
On this page:
https://deepmreye.slite.com/p/channel/MUgmvViEbaATSrqt3susLZ/notes/eKBt_91CH

> Training data can be acquired with camera-based eye tracking or by scanning eye-tracker calibration scripts (even without camera). We provide a sample script here: LINK.

The link is not an hyper link

I suspect it is this link: https://github.com/DeepMReye/Calibration

**Comment by Naubody** [comment]
Yes, correct. Still working on the documentation. The link is correct and has been added. Thank you!
