### ISSUE TITLE
could not install tensorflow dependency on apple M1

### ISSUE THREAD

**Issue by yyang1234** [DeepMReye/DeepMReye#23]
tried to install and got the following error

this seems to be due to the fact that I am using an M1 apple computer: see [here](https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776)

```
pip install git+https://github.com/DeepMReye/DeepMReye.git
Collecting git+https://github.com/DeepMReye/DeepMReye.git
  Cloning https://github.com/DeepMReye/DeepMReye.git to /private/var/folders/4s/b4y96bxd7n979w298f1q3nm40000gq/T/pip-req-build-f3a6j20h
  Running command git clone -q https://github.com/DeepMReye/DeepMReye.git /private/var/folders/4s/b4y96bxd7n979w298f1q3nm40000gq/T/pip-req-build-f3a6j20h
  Resolved https://github.com/DeepMReye/DeepMReye.git to commit 1c349e1c8477e4261f0de685c2d5ccb180dd7266
Collecting numpy
  Using cached numpy-1.23.3-cp39-cp39-macosx_11_0_arm64.whl (13.4 MB)
Collecting pandas
  Using cached pandas-1.5.0-cp39-cp39-macosx_11_0_arm64.whl (10.9 MB)
Collecting matplotlib
  Using cached matplotlib-3.6.0-cp39-cp39-macosx_11_0_arm64.whl (7.2 MB)
Collecting scipy
  Using cached scipy-1.9.1-cp39-cp39-macosx_12_0_arm64.whl (29.9 MB)
Collecting ipython
  Using cached ipython-8.5.0-py3-none-any.whl (752 kB)
Collecting plotly
  Using cached plotly-5.10.0-py2.py3-none-any.whl (15.2 MB)
Collecting scikit-learn
  Using cached scikit_learn-1.1.2-cp39-cp39-macosx_12_0_arm64.whl (7.7 MB)
Collecting antspyx
  Using cached antspyx-0.3.3.tar.gz (7.0 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.7 (from deepmreye) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.7
```

**Comment by Remi-Gau** [comment]
@yyang1234 and I found this one when trying to install bidsmreye on her laptop.

I suspect that for now the "easy" way is to work on #8 and update the README to suggest M1 owners to use a docker image of deepmreye.

Another option would be to see if there are ways to have different dependency requirements depending on the machine architecture but that sounds like maintenance hell.

**Comment by CYHSM** [comment]
Docker seems to be the way. Also, it will make sense to split the model into a TensorFlow/GPU-needed version and a simpler version which uses scikit-learn but does not need a GPU (the performance will go down though as the 3-D input needs to be flattened & SVM<CNN).

**Comment by Remi-Gau** [comment]
Do you mean several docker images in this case?

**Comment by Remi-Gau** [comment]
Or to have an install flag with several dependencies in each case?
