### ISSUE TITLE
Cannot Install ANTsPy on Device

### ISSUE THREAD

**Issue by tjhendrickson** [DeepMReye/DeepMReye#24]
Hello,

I'm having some serious issues installing ANTsPy. Based on some research it seems like it is very difficult to install ANTsPy on Centos 7 -- which is what I am using. It appears that ANTsPY has [docker images](https://github.com/ANTsX/ANTsPy/blob/master/tutorials/InstallingANTsPy.md#docker-installation) that can be used. Do you have any idea how difficult it would be to modify DeepMReye to incorporate a docker or singularity image of ANTsPy?

Best,

Tim

**Comment by Remi-Gau** [comment]
hey @tjhendrickson 

I have some of that as work in progress: see this issue: https://github.com/DeepMReye/DeepMReye/issues/8#issue-1075283217

Not taken the time to open a PR yet but given #23 this is becoming urgent.

If I manage to set something up, can I ping you to test it?

**Comment by tjhendrickson** [comment]
Absolutely, that would be excellent. Thanks @Remi-Gau!
