### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by yarikoptic** [DeepMReye/DeepMReye#29]
on GitHub and pypi. It would allow for establishing projects which would depend on this Python package.

**Comment by CYHSM** [comment]
Should be released now (see here [https://pypi.org/project/deepmreye/](https://pypi.org/project/deepmreye/)), sorry that it took so long. Thanks to @Remi-Gau for providing the necessary code changes for making this happen.

**Comment by yarikoptic** [comment]
wooohoo -- congrats and thank you!

I would advise also to tag and "release" on github.  I would recommend doing

- `git tag -a 0.1.1` locally (on the commit corresponding to the release), and providing brief description and/or changelog for the release inthere
- `git push origin 0.1.1` to push it to github
- go to https://github.com/DeepMReye/DeepMReye/releases, into tags, and make release from that tag

Github UI allows to create releases straight on the web UI, but those git tags then are not annotated, and thus not used by default by `git describe` so I do not like them and prefer the workflow suggested above (typically automated using intuit-auto or smth like our https://github.com/datalad/release-action/)

**Comment by CYHSM** [comment]
Cool thanks, that worked perfectly. I didn't add too much description but will hopefully remember to put a changelog in there from now on.

**Comment by yarikoptic** [comment]
so -- we must consider this issue addressed, thank you @CYHSM !

**Comment by Remi-Gau** [comment]
thanks for taking care of this @CYHSM ! 🚀 🤗

**Comment by Naubody** [comment]
Amazing, thank you @CYHSM!
