### ISSUE TITLE
Missing link to the models

### ISSUE THREAD

**Issue by Remi-Gau** [DeepMReye/DeepMReye#3]
On the training data page of the doc: 
https://deepmreye.slite.com/p/channel/MUgmvViEbaATSrqt3susLZ/notes/eKBt_91CH

> We are releasing a pre-trained version of DeepMReye that was trained on all datasets used in the paper, as well as models pre-trained on each of the individual datasets. Find these models here: LINK.

I suspect this is the link
https://osf.io/mrhk9/

**Comment by Naubody** [comment]
Yes, you will find them under https://osf.io/mrhk9/ in the folder model_weights. Added the correct link to the documentation. Thanks!
