### ISSUE TITLE
Issues on MacBooks with M1/M2 chips

### ISSUE THREAD

**Issue by Naubody** [DeepMReye/DeepMReye#31]
We are aware of installation issues of DeepMReye on Apple MacBooks with M1 or M2 chips.

The DeepLabCut team made us aware of a potential solution: Use miniconda3 instead of anaconda. https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/installation.md#install-anaconda-or-use-miniconda3-ideal-for-macos-users

We will be testing this soon, but if you have an M1/M2 MacBook and run into issues, please try out the suggested solution and let us know if it works.

**Comment by Naubody** [comment]
@layerfMRI: Could you/we try this soon on yours?

**Comment by layerfMRI** [comment]
Absolutely, I will try it tomorrow. If I fail, I will request you guidance again (e.g. via Zoom in the next days, or in person on Tuesday).

**Comment by Remi-Gau** [comment]
Other option is to use docker.
Should be more portable.
If not let me know and I can try to update the docker recipe to improve it.

**Comment by layerfMRI** [comment]
Yes thanks Remi, I am trying it with Docker now. 
I could build the image after removing the part in the docker file that looks for requirements.txt.
`COPY ["deepmreye", "setup.py", "README.md", "requirements.txt", "/deepmreye/"]`
I could not find the file on the latest version of code, nor the latest release. Maybe it can be removed.

**Comment by Remi-Gau** [comment]
Ouch. Forgot to test the docker build in some previous PR. Bad Remi.

Will fox that and maybe add a github workflow to test the docker build.

Other possibility woukd be to have a "stable" docker recipe that grabs deepmreye from pypi.

And a dev recipe that people have to build them selves after cloning the repo.

Also reminds me I should probably create a docker hub repo and push a deepmreye image there.

**Comment by Remi-Gau** [comment]
@layerfMRI also realizing that the docker recipe does not use the latest version of the trained model.

Will also fix that in the PR.

**Comment by Naubody** [comment]
Quick update on the M1/M2 issue. @layerfMRI and I just tried some things. 

We tried the miniconda solution as suggested [here](https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/installation.md#install-anaconda-or-use-miniconda3-ideal-for-macos-users) but it did not work either. We created a new environment and simply ran "pip install tensorflow", which crashed.

We then installed tensorflow manually using "conda install -c conda-forge tensorflow", and then ran "pip install deepmreye" afterwards. This worked - at least for the CPU version, which is good for the pertained model.

@layerfMRI will try it again with a clean environment and "pip install tensorflow-macos" for the GPU version soon.

**Comment by layerfMRI** [comment]
### Specific steps on the M1 Mac book were:

Install miniconda
```
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-MacOSX-arm64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
source ~/miniconda/bin/activate
conda init zsh
```

**Create environment** 
`conda create -n tensorflowtest python=3.9 
`And activate it 
`conda activate tensorflowtest 
`

**Install tensorflow**
`conda install -c conda-forge tensorflow
`This might not support GPU. Maybe its better to use instead: `pip install tensorflow-macos`


**Activate Environment again (after reboot)**
```
source ~/miniconda/bin/activate
conda activate tensorflowtest 
```

**In Visual studio Code, set variable**
-> Ctrl+Shift+p
-> Python select interpreter 
/Users/administrator/miniconda/envs/tensorflowtest/bin 

**Open Jupyter notebook from github example** 
/Users/administrator/Desktop/eyetracking/DeepMReye/notebooks

**Comment by Remi-Gau** [comment]
@Naubody if someone with admin rights to the deepmreye orga can set up circle-ci we should be able to soon be able to docker pull deepmreye instead of letting users install it.

**Comment by CYHSM** [comment]
Done (https://github.com/DeepMReye/DeepMReye/pull/32#issuecomment-1380460863)
