### ISSUE TITLE
Missing link to the coregistration code

### ISSUE THREAD

**Issue by Remi-Gau** [DeepMReye/DeepMReye#4]
on the Input & preprocessing page of the doc
https://deepmreye.slite.com/p/channel/MUgmvViEbaATSrqt3susLZ/notes/cHQpFuNTG

See line:

> The code for the coregistration can be found here: ADD LINK

I assume this is the code in question:

https://github.com/DeepMReye/DeepMReye/blob/main/deepmreye/preprocess.py

**Comment by Naubody** [comment]
Hi Remi, yes, correct - Thank you! The documentation includes the missing link now.
