### ISSUE TITLE
Typo in deepmreye_example_usage_pretrained_weights.ipynb

### ISSUE THREAD

**Issue by linus-md** [DeepMReye/DeepMReye#40]
Hello,

in the project structure it says: 

└── model_weights
    └── datasets_1to**5**.h5

but you continue to load:

model_weights = os.path.join(experiment_folder, "model_weights", "datasets_1to**6**.h5")

I think it should say 5 as well. :)

Best,
Linus

**Comment by Naubody** [comment]
Fixed. Thanks Linus!

**Comment by Remi-Gau** [comment]
I think both should actually say `datasets_1to6.h5` because right the CI is broken otherwise
