### ISSUE TITLE
consider adding some minimal code styling

### ISSUE THREAD

**Issue by Remi-Gau** [DeepMReye/DeepMReye#44]
I am a big fan of black for formatting and using isort for imports.

And running flake8 or some sort of linter would also be good.

**Comment by CYHSM** [comment]
Yeah, I'm thinking about adding a pre-commit yaml file that every collaborator can use (this would mean that we enforce the use of [pre-commit](https://pre-commit.com/) though). Will add a PR with the exact configuration, then we can discuss there.

**Comment by Remi-Gau** [comment]
that sounds like music to my ears

you can also sign up to pre-commit ci so that the CI will do the checks and even push the fixes automatically when it can

I use in almost everywhere I can and saves you the trouble from setting the github CI to check style and everything else

https://pre-commit.ci/

**Comment by Remi-Gau** [comment]
closed by #45
