### ISSUE TITLE
Deepmreye_example_usage_pretrained_weights fails at train model

### ISSUE THREAD

**Issue by angusolav** [DeepMReye/DeepMReye#81]
I am having some issues with the DeepMreye demo using the exemplary data from the 2 first participants from the sample dataset as instructed in the notebook "deepmreye_example_usage_pretrained_model_weights.

I am using anaconda with python 3.9.19. I am running it on CPU so I have set CUDA_VISIBLE_DEVICES = "".
Also, I have modified the architecture.py script so that `x = AveragePooling3D(pool_size=(2, 2, 2))(x)`.

Preprocessing seems to work fine, although I get "Mean of empty slice" and "Degrees of freedom <= 0 for slice" for sub-NDARAA948VFH during the "# Loop across participants and extract eye masks".

The issue arises during "#Get utrained model and load with trained weights", running train.train_model (error report 1).

I have tried to resolve this issue by changing architecture.py code according to file changes under Remi-Gau's issue "[MAINT] run CI on python 3.12", but get another error (error report 2).

All pip install packages versions in the deepmreye environment is listed at the bottom.

Have anyone else experienced this issue? I am not a very experienced coder so I am sorry if there is some obvious solution here. Thanks! :)

## Error Report 1

```
WARNING:tensorflow:From C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From C:\Users/angusow/DeepMReye\deepmreye\train.py:64: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 2
      1 # Get untrained model and load with trained weights
----> 2 (model, model_inference) = train.train_model(dataset="example_data",
      3                                              generators=generators,
      4                                              opts=opts,
      5                                              return_untrained=True)
      6 model_inference.load_weights(model_weights)

File C:\Users/angusow/DeepMReye\deepmreye\train.py:94, in train_model(dataset, generators, opts, clear_graph, save, model_path, workers, use_multiprocessing, models, return_untrained, verbose)
     92 # Get model
     93 if models is None:
---> 94     model, model_inference = architecture.create_standard_model(X.shape[1::], opts)
     95 else:
     96     model, model_inference = models

File C:\Users/angusow/DeepMReye\deepmreye\architecture.py:87, in create_standard_model(input_shape, opts)
     77 out_confidence = confidence_block(
     78     bottleneck_layer,
     79     num_fc=opts["num_fc"],
   (...)
     83     mc_dropout=opts["mc_dropout"],
     84 )
     86 # Create model
---> 87 real_regression_shape = out_regression.shape.as_list()
     88 real_regression = Input(real_regression_shape[1::])
     89 model = Model(inputs=[input_layer, real_regression], outputs=[out_regression])

AttributeError: 'tuple' object has no attribute 'as_list'
```

## Error report 2

```
ValueError                                Traceback (most recent call last)
Cell In[10], line 2
      1 # Get untrained model and load with trained weights
----> 2 (model, model_inference) = train.train_model(dataset="example_data",
      3                                              generators=generators,
      4                                              opts=opts,
      5                                              return_untrained=True)
      6 model_inference.load_weights(model_weights)

File C:\Users/angusow/DeepMReye\deepmreye\train.py:94, in train_model(dataset, generators, opts, clear_graph, save, model_path, workers, use_multiprocessing, models, return_untrained, verbose)
     92 # Get model
     93 if models is None:
---> 94     model, model_inference = architecture.create_standard_model(X.shape[1::], opts)
     95 else:
     96     model, model_inference = models

File C:\Users/angusow/DeepMReye\deepmreye\architecture.py:93, in create_standard_model(input_shape, opts)
     90 model_inference = Model(inputs=input_layer, outputs=[out_regression, out_confidence])
     92 # Add losses
---> 93 loss_euclidean, loss_confidence = compute_standard_loss(out_confidence, real_regression, out_regression)
     94 model.add_loss(opts["loss_euclidean"] * loss_euclidean)
     95 model.add_loss(opts["loss_confidence"] * loss_confidence)

File C:\Users/angusow/DeepMReye\deepmreye\architecture.py:196, in compute_standard_loss(out_confidence, real_reg, pred_reg)
    195 def compute_standard_loss(out_confidence, real_reg, pred_reg):
--> 196     loss_euclidean = euclidean_distance(real_reg, pred_reg)
    197     loss_confidence = mean_squared_error(loss_euclidean, out_confidence)
    199     return K.mean(loss_euclidean), K.mean(loss_confidence)

File C:\Users/angusow/DeepMReye\deepmreye\architecture.py:203, in euclidean_distance(y_true, y_pred)
    202 def euclidean_distance(y_true, y_pred):
--> 203     return tf.sqrt(K.sum(K.square(y_true - y_pred), axis=-1))

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\keras\src\legacy\backend.py:2078, in square(x)
   2075 @keras_export("keras._legacy.backend.square")
   2076 def square(x):
   2077     """DEPRECATED."""
-> 2078     return tf.square(x)

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\tensorflow\python\ops\weak_tensor_ops.py:88, in weak_tensor_unary_op_wrapper.<locals>.wrapper(*args, **kwargs)
     86 def wrapper(*args, **kwargs):
     87   if not ops.is_auto_dtype_conversion_enabled():
---> 88     return op(*args, **kwargs)
     89   bound_arguments = signature.bind(*args, **kwargs)
     90   bound_arguments.apply_defaults()

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:13363, in square(x, name)
  13361   if _result is not NotImplemented:
  13362     return _result
> 13363   return square_eager_fallback(
  13364       x, name=name, ctx=_ctx)
  13365 except _core._SymbolicException:
  13366   pass  # Add nodes to the TensorFlow graph.

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:13404, in square_eager_fallback(x, name, ctx)
  13403 def square_eager_fallback(x: Annotated[Any, TV_Square_T], name, ctx) -> Annotated[Any, TV_Square_T]:
> 13404   _attr_T, (x,) = _execute.args_to_matching_eager([x], ctx, [_dtypes.bfloat16, _dtypes.half, _dtypes.float32, _dtypes.float64, _dtypes.int8, _dtypes.int16, _dtypes.int32, _dtypes.int64, _dtypes.uint8, _dtypes.uint16, _dtypes.uint32, _dtypes.uint64, _dtypes.complex64, _dtypes.complex128, ])
  13405   _inputs_flat = [x]
  13406   _attrs = ("T", _attr_T)

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\tensorflow\python\eager\execute.py:251, in args_to_matching_eager(***failed resolving arguments***)
    247 # First see if we can get a valid dtype with the default conversion
    248 # and see if it matches an allowed dtypes. Some ops like ConcatV2 may
    249 # not list allowed dtypes, in which case we should skip this.
    250 if dtype is None and allowed_dtypes:
--> 251   tensor = tensor_conversion_registry.convert(t)
    252   # If we did not match an allowed dtype, try again with the default
    253   # dtype. This could be because we have an empty tensor and thus we
    254   # picked the wrong type.
    255   if tensor.dtype not in allowed_dtypes:

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\tensorflow\python\framework\tensor_conversion_registry.py:209, in convert(value, dtype, name, as_ref, preferred_dtype, accepted_result_types)
    207 overload = getattr(value, "__tf_tensor__", None)
    208 if overload is not None:
--> 209   return overload(dtype, name)  #  pylint: disable=not-callable
    211 for base_type, conversion_func in get(type(value)):
    212   # If dtype is None but preferred_dtype is not None, we try to
    213   # cast to preferred_dtype first.
    214   ret = None

File ~\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\keras\src\backend\common\keras_tensor.py:138, in KerasTensor.__tf_tensor__(self, dtype, name)
    137 def __tf_tensor__(self, dtype=None, name=None):
--> 138     raise ValueError(
    139         "A KerasTensor cannot be used as input to a TensorFlow function. "
    140         "A KerasTensor is a symbolic placeholder for a shape and dtype, "
    141         "used when constructing Keras Functional models "
    142         "or Keras Functions. You can only use it as input to a Keras layer "
    143         "or a Keras operation (from the namespaces `keras.layers` "
    144         "and `keras.operations`). "
    145         "You are likely doing something like:\n\n"
    146         "```\n"
    147         "x = Input(...)\n"
    148         "...\n"
    149         "tf_fn(x)  # Invalid.\n"
    150         "```\n\n"
    151         "What you should do instead is wrap `tf_fn` in a layer:\n\n"
    152         "```\n"
    153         "class MyLayer(Layer):\n"
    154         "    def call(self, x):\n"
    155         "        return tf_fn(x)\n\n"
    156         "x = MyLayer()(x)\n"
    157         "```\n"
    158     )

ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

x = Input(...)
...
tf_fn(x)  # Invalid.

What you should do instead is wrap `tf_fn` in a layer:

class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```

```bash
# Pip list
(deepmreye) C:\Users\angusow>pip list
Package                      Version
---------------------------- --------------
absl-py                      2.1.0
antspyx                      0.4.2
anyio                        4.2.0
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.0.5
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.1.0
Babel                        2.11.0
backcall                     0.2.0
beautifulsoup4               4.12.3
bleach                       4.1.0
Brotli                       1.0.9
certifi                      2024.8.30
cffi                         1.17.1
charset-normalizer           3.3.2
chart-studio                 1.1.0
cmake                        3.30.4
colorama                     0.4.6
comm                         0.2.1
contourpy                    1.3.0
cycler                       0.12.1
debugpy                      1.6.7
decorator                    5.1.1
deepmreye                    0.2.1
defusedxml                   0.7.1
exceptiongroup               1.2.0
executing                    0.8.3
fastjsonschema               2.16.2
flatbuffers                  24.3.25
fonttools                    4.54.1
fqdn                         1.5.1
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.66.2
h11                          0.14.0
h5py                         3.12.1
httpcore                     1.0.2
httpx                        0.27.0
idna                         3.10
imageio                      2.35.1
importlib-metadata           7.0.1
importlib_resources          6.4.5
ipykernel                    6.28.0
ipython                      8.15.0
ipywidgets                   8.1.2
isoduration                  20.11.0
jedi                         0.19.1
Jinja2                       3.1.4
joblib                       1.4.2
json5                        0.9.25
jsonpointer                  3.0.0
jsonschema                   4.19.2
jsonschema-specifications    2023.12.1
jupyter                      1.0.0
jupyter_client               8.6.0
jupyter-console              6.6.3
jupyter_core                 5.7.2
jupyter-events               0.10.0
jupyter-lsp                  2.2.0
jupyter_server               2.14.1
jupyter_server_terminals     0.4.4
jupyterlab                   4.2.5
jupyterlab-pygments          0.1.2
jupyterlab_server            2.27.3
jupyterlab-widgets           3.0.10
keras                        3.5.0
kiwisolver                   1.4.7
lazy_loader                  0.4
libclang                     18.1.1
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   2.1.3
matplotlib                   3.9.2
matplotlib-inline            0.1.6
mdurl                        0.1.2
mistune                      2.0.4
ml-dtypes                    0.4.1
namex                        0.0.8
nbclient                     0.10.0
nbconvert                    7.10.0
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.2.1
nibabel                      5.2.1
notebook                     7.2.2
notebook_shim                0.2.3
numpy                        1.26.4
opt_einsum                   3.4.0
optree                       0.12.1
overrides                    7.4.0
packaging                    24.1
pandas                       2.2.3
pandocfilters                1.5.0
parso                        0.8.3
patsy                        0.5.6
pickleshare                  0.7.5
pillow                       10.4.0
pip                          24.2
platformdirs                 3.10.0
plotly                       5.24.1
ply                          3.11
prometheus-client            0.14.1
prompt-toolkit               3.0.43
protobuf                     4.25.5
psutil                       5.9.0
pure-eval                    0.2.2
pycparser                    2.21
Pygments                     2.15.1
pyparsing                    3.1.4
PyQt5                        5.15.10
PyQt5-sip                    12.13.0
PySocks                      1.7.1
python-dateutil              2.9.0.post0
python-json-logger           2.0.7
pytz                         2024.1
pywin32                      305.1
pywinpty                     2.0.10
PyYAML                       6.0.1
pyzmq                        25.1.2
qtconsole                    5.6.0
QtPy                         2.4.1
referencing                  0.30.2
requests                     2.32.3
retrying                     1.3.4
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.8.1
rpds-py                      0.10.6
scikit-image                 0.24.0
scikit-learn                 1.5.2
scipy                        1.13.1
Send2Trash                   1.8.2
setuptools                   75.1.0
sip                          6.7.12
six                          1.16.0
sniffio                      1.3.0
soupsieve                    2.5
stack-data                   0.2.0
statsmodels                  0.14.3
tenacity                     9.0.0
tensorboard                  2.17.1
tensorboard-data-server      0.7.2
tensorflow                   2.17.0
tensorflow-intel             2.17.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
terminado                    0.17.1
threadpoolctl                3.5.0
tifffile                     2024.8.30
tinycss2                     1.2.1
tomli                        2.0.1
tornado                      6.4.1
traitlets                    5.14.3
types-python-dateutil        2.9.0.20240906
typing_extensions            4.11.0
tzdata                       2024.2
uri-template                 1.3.0
urllib3                      2.2.2
wcwidth                      0.2.13
webcolors                    24.8.0
webencodings                 0.5.1
websocket-client             1.8.0
Werkzeug                     3.0.4
wheel                        0.44.0
widgetsnbextension           4.0.10
win-inet-pton                1.1.0
wrapt                        1.16.0
zipp                         3.17.0
```

**Comment by Remi-Gau** [comment]
hey @angusolav 
will just reformat your post a bit for readability

**Comment by Remi-Gau** [comment]
Just to make sure, can you test this on the main branch of the repository (I think that https://github.com/DeepMReye/DeepMReye/pull/76 includes one of your fixes).

I think the following should do it

```bash
pip install git+https://github.com/DeepMReye/DeepMReye
```

**Comment by angusolav** [comment]
Thanks you, this seems to work! May I also ask if you know what has gone wrong here during model evaluation:

(evaluation, scores) = train.evaluate_model(
    dataset="example_data",
    model=model_inference,
    generators=generators,
    save=False,
    model_path=experiment_folder,
    model_description="",
    verbose=2,
    percentile_cut=80,
)

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide


1 / 2 - Model Performance for C:\Users\angusow\DeepMReye\notebooks\processed_data/sub-NDARAA948VFHno_label.npz
              Pearson          R^2-Score             Eucl. Error             
                    X   Y Mean         X     Y  Mean        Mean Median   Std
Default           NaN NaN  NaN     0.000 0.000 0.000       4.682  4.875 2.557
Default subTR     NaN NaN  NaN     0.000 0.000 0.000       4.683  4.876 2.554
Refined           NaN NaN  NaN     0.000 0.000 0.000       5.286  5.690 2.424
Refined subTR     NaN NaN  NaN     0.000 0.000 0.000       5.279  5.698 2.426


2 / 2 - Model Performance for C:\Users\angusow\DeepMReye\notebooks\processed_data/sub-NDARAC349YUCno_label.npz
              Pearson          R^2-Score             Eucl. Error             
                    X   Y Mean         X     Y  Mean        Mean Median   Std
Default           NaN NaN  NaN     0.000 0.000 0.000       5.083  5.115 2.450
Default subTR     NaN NaN  NaN     0.000 0.000 0.000       5.077  5.124 2.452
Refined           NaN NaN  NaN     0.000 0.000 0.000       5.393  5.782 2.524
Refined subTR     NaN NaN  NaN     0.000 0.000 0.000       5.382  5.760 2.531

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

C:\Users\angusow\AppData\Local\anaconda3\envs\deepmreye\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

**Comment by Remi-Gau** [comment]
you mean the 

```
RuntimeWarning:

invalid value encountered in divide
```

not sure

@CYHSM any idea?

**Comment by Remi-Gau** [comment]
> Thanks you, this seems to work!

OK that means we probably need to push a new release to pypi so you can just install it from there.

**Comment by CYHSM** [comment]
> you mean the
> 
> ```
> RuntimeWarning:
> 
> invalid value encountered in divide
> ```
> 
> not sure
> 
> @CYHSM any idea?

This sounds like the computation of the Pearson correlation goes wrong, likely due to the standard deviation being 0. @angusolav how many TRs do you use here?

**Comment by angusolav** [comment]
I am using the experimental data referenced in the notebook. The TRs should be 800ms and there are 135 of them in the origional nifti files. This becomes 270 after preprocessing steps.

**Comment by CYHSM** [comment]
I see, thanks. Will look into this!

**Comment by cannon10** [comment]
@angusolav The error message "AttributeError: 'tuple' object has no attribute 'as_list'“，I've encountered the same issue and have tried many methods without success. Have you found a solution? If so, could you please share it with me? I would be very grateful.

**Comment by cannon10** [comment]
@angusolav Thank you very much for your help, and of course, Remi-Gau, for finally solving the problem that has been bothering me for two or three days. With this issue resolved, I've encountered a new one: 

Exception in thread Thread-4 (_run):
Traceback (most recent call last):
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\site-packages\keras\src\utils\data_utils.py", line 959, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\site-packages\keras\src\utils\data_utils.py", line 946, in pool_fn
    pool = get_pool_class(True)(
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\pool.py", line 215, in __init__
    self._repopulate_pool()
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\process.py", line 121, in start
...
    reduction.dump(process_obj, to_child)
  File "c:\Users\coYQ\anaconda3\envs\deepmreye\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object

due to my inexperience as a beginner, I'm not handling this situation very well and just tried to set the workers parameter to 0 to avoid using multiprocessing, which resulted in an excessively long training time. I'm wondering if you've encountered the same issue, and if so, I would also love to receive your assistance.

**Comment by Remi-Gau** [comment]
@cannon10 
Can you tell us what code you were running? on what data?

**Comment by cannon10** [comment]
@Remi-Gau 
Apologies for not expressing my question clearly. The code I am currently running is from the "deepmreye_example_usage.ipynb" notebook, specifically the line:
(model, model_inference) = train.train_model(
    dataset="example_data",
    generators=generators,
    opts=opts,
    use_multiprocessing=True,
    return_untrained=False,
    verbose=1,
    save=True,
    model_path=model_weights,
)
The data I am using is also provided by the Data Repository in DeepMReye.

**Comment by Naubody** [comment]
Hi @angusolav, was this issue resolved?

**Comment by angusolav** [comment]
@Naubody Yes, thank you! :)
